sudo: false
language: python
python:
    - pypy3
before_install:
  # There are TravisCI provided versions of PyPy and PyPy3, but currently too old.
  # We therefore deactivate that, and download and unzip portable PyPy binaries.
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then
        deactivate
        cd ..
        wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2
        tar -jxf pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2
        echo 'Setting up aliases...'
        cd pypy3.5-6.0.0-linux_x86_64-portable/bin/
        export PATH=$PWD:$PATH
        ln -s pypy3 python
        echo 'Setting up pip...'
        ./pypy3 -m ensurepip
        ln -s pip3 pip
        cd ../../the-law-factory-parser
        python --version
        pip --version
    fi
install: pip install -r test_requirements.txt
script:
   - set -e # exit on first fail: see https://github.com/travis-ci/travis-ci/issues/1066
   - flake8 --ignore=E501,F405,F403,F401,F841 --select=F . # mainly detect undefined variables
   - coverage run --include="./*.py" tools/sort_articles.py
   - coverage run -a --include="./*.py" tools/parse_texte.py --test
   - coverage run -a --include="./*.py" tests/test_steps.py
   - git clone https://github.com/regardscitoyens/the-law-factory-parser-test-cases.git tests_cases
   - coverage run -a --include="./*.py" tests/test_regressions.py tests_cases
   - set +e
after_success:
   - coveralls
